// flow-typed signature: 67cc1c418c5a713579a91a9ecd58a915
// flow-typed version: <<STUB>>/react-split_v^2.0.7/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-split'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-split' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-split/dist/react-split.es' {
  declare module.exports: any;
}

declare module 'react-split/dist/react-split' {
  declare module.exports: any;
}

declare module 'react-split/dist/react-split.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-split/dist/react-split.es.js' {
  declare module.exports: $Exports<'react-split/dist/react-split.es'>;
}
declare module 'react-split/dist/react-split.js' {
  declare module.exports: $Exports<'react-split/dist/react-split'>;
}
declare module 'react-split/dist/react-split.min.js' {
  declare module.exports: $Exports<'react-split/dist/react-split.min'>;
}
